rbac:
  create: true
controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-internal: false
  stats:
    enabled: true
  metrics:
    port: 10254
    # if this port is changed, change healthz-port: in extraArgs: accordingly
    enabled: false

    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
  publishService:
    enabled: true
