"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "application"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "kubeflow"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "path": "application/v3"
    "repoURL": "https://github.com/kubeflow/manifests"
    "targetRevision": "v1.1-branch"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
    "syncOptions":
    - "CreateNamespace=true"
